
namespace: "flink-dev"
imagepullsecrets: ""
dockerhub: ""
repository: "divyagovindaiah123/flink-sanketika-obsrv" 
image_tag: "1.0.0"
serviceMonitor:
  enabled: false
replicaCount: 1

jobmanager:
  rpc_port: 6123
  blob_port: 6124
  query_port: 6125
  ui_port: 8081
  prom_port: 9250
  heap_memory: 1024

rest_port: 80
resttcp_port: 8081
service:
  type: ClusterIP


taskmanager:
  prom_port: 9251
  rpc_port: 6122
  heap_memory: 1024
  replicas: 1
  cpu_requests: 0.3

checkpoint_store_type: ""

# AWS S3 Details
s3_access_key: ""
s3_secret_key: ""
s3_endpoint: ""
s3_path_style_access: ""


dataset_registry: |
  postgres {
    host = postgresql.postgresql.svc.cluster.local
    port = 5432
    maxConnections = 2
    user = "postgres"
    password = "postgres"
    database = "obsrv"
  }
log4j_console_properties: |
  # This affects logging for both user code and Flink
  rootLogger.level = INFO
  rootLogger.appenderRef.console.ref = ConsoleAppender
  # Uncomment this if you want to _only_ change Flink's logging
  #logger.flink.name = org.apache.flink
  #logger.flink.level = INFO
  # The following lines keep the log level of common libraries/connectors on
  # log level INFO. The root logger does not override this. You have to manually
  # change the log levels here.
  logger.akka.name = akka
  logger.akka.level = ERROR
  logger.kafka.name= org.apache.kafka
  logger.kafka.level = ERROR
  logger.hadoop.name = org.apache.hadoop
  logger.hadoop.level = ERROR
  logger.zookeeper.name = org.apache.zookeeper
  logger.zookeeper.level = ERROR
  # Log all infos to the console
  appender.console.name = ConsoleAppender
  appender.console.type = CONSOLE
  appender.console.layout.type = PatternLayout
  appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss,SSS} %-5p %-60c %x - %m%n
  # Suppress the irrelevant (wrong) warnings from the Netty channel handler
  logger.netty.name = org.apache.flink.shaded.akka.org.jboss.netty.channel.DefaultChannelPipeline
  logger.netty.level = OFF
base_config: |
  kafka {
    broker-servers = "kafka-headless.kafka.svc.cluster.local:9092"
    producer.broker-servers = "kafka-headless.kafka.svc.cluster.local:9092"
    consumer.broker-servers = "kafka-headless.kafka.svc.cluster.local:9092"
    zookeeper = "kafka-zookeeper-headless.svc.cluster.local:2181"
    producer {
      max-request-size = 1572864
      batch.size = 98304
      linger.ms = 10
      compression = "snappy"
    }
    output.system.event.topic = "dev.system.events"
  }
  job {
    env = "dev"
    enable.distributed.checkpointing = false
    statebackend {
      blob {
        storage {
          account = "obsrvacc.blob.core.windows.net"
          container = "obsrv-data-storage"
          checkpointing.dir = "checkpoint"
        }
      }
      base.url = ""
    }
  }
  task {
    parallelism = 1
    consumer.parallelism = 1
    checkpointing.compressed = true
    checkpointing.interval = 10
    checkpointing.pause.between.seconds = 3000
    restart-strategy.attempts = 3
    restart-strategy.delay = 30000 # in milli-seconds
  }
  redis.connection.timeout = 100
  redis {
    host = obsrv-redis.redis.svc.cluster.local
    port = 6379
  }
  redis-meta {
    host = obsrv-redis.redis.svc.cluster.local
    port = 6379
  }
  postgres {
    host = postgresql.postgresql.svc.cluster.local
    port = 5432
    maxConnections = 2
    user = "postgres"
    password = "postgres"
  }
merged-pipeline:
  merged-pipeline: |+
    include file("/data/flink/conf/base-config.conf")
    include file("/data/flink/conf/dataset-registry.conf")
    kafka {
      input.topic = "dev.ingest"
      output.raw.topic = "dev.raw"
      output.extractor.duplicate.topic = "dev.extractor.duplicate"
      output.failed.topic = "dev.failed"
      output.batch.failed.topic = "dev.extractor.failed"
      event.max.size = "1048576" # Max is only 1MB
      output.invalid.topic = "dev.invalid"
      output.unique.topic = "dev.unique"
      output.duplicate.topic = "dev.duplicate"
      output.denorm.topic = "dev.denorm"
      output.denorm.failed.topic = "dev.denorm.failed"
      output.transform.topic = "dev.transform"
      stats.topic = "dev.stats"
      groupId = "dev-single-pipeline-group"
      producer {
        max-request-size = 5242880
      }
    }
    task {
      window.time.in.seconds = 5
      window.count = 30
      window.shards = 1400
      consumer.parallelism = 1
      downstream.operators.parallelism = 1
    }
    
    redis {
      database {
        extractor.duplication.store.id = 1
        preprocessor.duplication.store.id = 2
        key.expiry.seconds = 3600
      }
    }
  flink-conf: |+
    jobmanager.memory.flink.size: 1024m
    taskmanager.memory.flink.size: 1024m
    taskmanager.numberOfTaskSlots: 1
    jobManager.numberOfTaskSlots: 1
    parallelism.default: 1
    jobmanager.execution.failover-strategy: region
    taskmanager.memory.network.fraction: 0.1
    scheduler-mode: reactive
    heartbeat.timeout: 8000
    heartbeat.interval: 5000
    taskmanager.memory.process.size: 1700m
    jobmanager.memory.process.size: 1600m
    # classloader.resolve-order: "parent-first"
    # state.savepoints.dir: file:///tmp
job_classname: org.sunbird.obsrv.pipeline.task.MergedPipelineStreamTask


transformer:
  transformer: |+
    include file("/data/flink/conf/base-config.conf")
    include file("/data/flink/conf/dataset-registry.conf")

    kafka {
      input.topic = "dev.denorm"
      output.transform.topic = "dev.transform"
      groupId = "dev-transformer-group"
      producer {
        max-request-size = 5242880
      }
    }

    task {
      consumer.parallelism = 1
      downstream.operators.parallelism = 1
    }
  
  flink-conf: |+
    jobmanager.memory.flink.size: 1024m
    jobmanager.heap.size: 512m
    taskmanager.memory.flink.size: 1024m
    taskmanager.numberOfTaskSlots: 1
    jobManager.numberOfTaskSlots: 1
    parallelism.default: 1
    jobmanager.execution.failover-strategy: region
    taskmanager.memory.network.fraction: 0.1
    scheduler-mode: reactive
    heartbeat.timeout: 8000
    heartbeat.interval: 5000
    taskmanager.memory.process.size: 1700m
  jobmanager.memory.process.size: 1600m
job_classname: "org.sunbird.obsrv.transformer.task.TransformerStreamTas"


preprocessor: 
  preprocessor: |+
    include file("/data/flink/conf/base-config.conf")
    kafka {
      input.topic = ${.raw"
      output.failed.topic = "dev.failed"
      output.invalid.topic = "dev.invalid"
      output.unique.topic = "dev.unique"
      output.duplicate.topic = "dev.duplicate"
      groupId = "dev-pipeline-preprocessor-group"
    }

    task {
      consumer.parallelism = 1
      downstream.operators.parallelism = 1
    }

    redis {
      database {
        preprocessor.duplication.store.id = 2
        key.expiry.seconds = 3600
      }
    }
  flink-conf: |+
    jobmanager.memory.flink.size: 1024m
    taskmanager.memory.flink.size: 1024m
    taskmanager.numberOfTaskSlots: 1
    jobManager.numberOfTaskSlots: 1
    parallelism.default: 1
    jobmanager.execution.failover-strategy: region
    taskmanager.memory.network.fraction: 0.1
    scheduler-mode: reactive
    heartbeat.timeout: 8000
    heartbeat.interval: 5000
    taskmanager.memory.process.size: 1700m
    jobmanager.memory.process.size: 1600m 

job_classname: "org.sunbird.obsrv.preprocessor.task.PipelinePreprocessorStreamTask"


extractor: 
  extractor: |+
    include file("/data/flink/conf/base-config.conf")
    kafka {
      input.topic = "dev.ingest"
      output.raw.topic = "dev.raw"
      output.extractor.duplicate.topic = "dev.extractor.duplicate"
      output.failed.topic = "dev.failed"
      output.batch.failed.topic = "dev.extractor.failed"
      event.max.size = "1048576" # Max is only 1MB
      groupId = "dev-extractor-group"
      producer {
        max-request-size = 5242880
      }
    }

    task {
      consumer.parallelism = 1
      downstream.operators.parallelism = 1
    }

    redis {
      database {
        extractor.duplication.store.id = 1
        key.expiry.seconds = 3600
      }
    }
  flink-conf: |+
    jobmanager.memory.flink.size: 1024m
    taskmanager.memory.flink.size: 1024m
    taskmanager.numberOfTaskSlots: 1
    jobManager.numberOfTaskSlots: 1
    parallelism.default: 1
    jobmanager.execution.failover-strategy: region
    taskmanager.memory.network.fraction: 0.1
    scheduler-mode: reactive
    heartbeat.timeout: 8000
    heartbeat.interval: 5000
    taskmanager.memory.process.size: 1700m
    jobmanager.memory.process.size: 1600m     
  
job_classname: "org.sunbird.obsrv.extractor.task.ExtractorStreamTask"


druid-router:
  druid-router: |+
    include file("/data/flink/conf/base-config.conf")
    kafka {
      input.topic = dev".transform"
      stats.topic = dev".stats"
      groupId = dev"-druid-router-group"
    }

    task {
      consumer.parallelism = 1
      downstream.operators.parallelism = 1
    }
  flink-conf: |+
    jobmanager.memory.flink.size: 1024m
    taskmanager.memory.flink.size: 1024m
    taskmanager.numberOfTaskSlots: 1
    jobManager.numberOfTaskSlots: 1
    parallelism.default: 1
    jobmanager.execution.failover-strategy: region
    taskmanager.memory.network.fraction: 0.1
    scheduler-mode: reactive
    heartbeat.timeout: 8000
    heartbeat.interval: 5000
    taskmanager.memory.process.size: 1700m
    jobmanager.memory.process.size: 1600m   
job_classname: "org.sunbird.obsrv.router.task.DruidRouterStreamTask"


denormalizer: 
  denormalizer: |+
    include file("/data/flink/conf/base-config.conf")
    kafka {
      input.topic = "dev.unique"
      output.denorm.topic = "dev.denorm"
      output.denorm.failed.topic = "dev.denorm.failed"
      groupId = "dev-denormalizer-group"
    }

    task {
      window.time.in.seconds = 5
      window.count = 30
      window.shards = 1400
      consumer.parallelism = 1
      downstream.operators.parallelism = 1
    }
  flink-conf: |+
    jobmanager.memory.flink.size: 1024m
    taskmanager.memory.flink.size: 1024m
    taskmanager.numberOfTaskSlots: 1
    jobManager.numberOfTaskSlots: 1
    parallelism.default: 1
    jobmanager.execution.failover-strategy: region
    taskmanager.memory.network.fraction: 0.1
    scheduler-mode: reactive
    heartbeat.timeout: 8000
    heartbeat.interval: 5000
    taskmanager.memory.process.size: 1700m
    jobmanager.memory.process.size: 1600m     
job_classname: "org.sunbird.obsrv.denormalizer.task.DenormalizerWindowStreamTask"
